# --- Config ---
# INTENT: Confirmation tests for the large-file truncation root cause. Three
#   targeted tests, each changing ONE variable from the failing run:
#     TEST 1 (H1 confirm): arrow::read_parquet(url) with options(timeout = 600).
#       Same code path that failed (download.file under the hood) — only the
#       timeout raised. If it now completes, H1 is CONFIRMED.
#     TEST 2 (H3): does arrow use its OWN C++ HTTP client, bypassing R's socket
#       timeout? Probe by reading with the DEFAULT 60s timeout but via an
#       explicit arrow FileSystem URL — if arrow had a native HTTP client it
#       would ignore getOption('timeout'). (Expectation: arrow has NO native
#       HTTP client for bare https:// parquet; it delegates to download.file.)
#     TEST 3 (robust pattern): curl::multi_download() — a resumable, progress-
#       aware downloader independent of getOption('timeout') — as the
#       recommended large-file fetch. Download to scratch ONCE.
# REASONING: Diagnostic 01 measured 1.40 MB/s => ~153s full transfer, well past
#   the 60s default. This script proves the fix and validates a robust pattern.
# ASSUMES: network egress allowed; ~214MB scratch space available; view-safe
#   cast needed only if this file is view-typed (checked post-read).
# STAGE: debug

library(arrow)
library(curl)

URL <- "https://huggingface.co/datasets/brhkim/education_data_portal_mirror/resolve/main/ccd/schools_ccd_directory.parquet"
SCRATCH <- "/daaf/research/2026-07-11_FrameworkDev_MirrorParquetCompat/scripts/scratch"
DEST <- file.path(SCRATCH, "ccd_directory_multidownload.parquet")
REPORTED_BYTES <- 224216539

dir.create(SCRATCH, recursive = TRUE, showWarnings = FALSE)

# =====================================================================
# TEST 3 FIRST (robust pattern) — get the file on disk ONCE, then reuse.
# curl::multi_download resumes, streams to disk, and does NOT use R's
# getOption('timeout'); it uses libcurl's own low-speed / connect timeouts.
# =====================================================================
cat("=== TEST 3: curl::multi_download() (robust large-file fetch) ===\n")
t0 <- Sys.time()
dl <- tryCatch(
  curl::multi_download(URL, DEST, resume = TRUE),
  error = function(e) { cat("multi_download error:", conditionMessage(e), "\n"); NULL }
)
if (!is.null(dl)) {
  elapsed <- as.numeric(difftime(Sys.time(), t0, units = "secs"))
  on_disk <- if (file.exists(DEST)) file.info(DEST)$size else NA_real_
  cat(sprintf("success      : %s\n", dl$success))
  cat(sprintf("status_code  : %s\n", dl$status_code))
  cat(sprintf("downloaded   : %s bytes\n", format(dl$downloaded, big.mark = ",")))
  cat(sprintf("on-disk size : %s bytes\n", format(on_disk, big.mark = ",")))
  cat(sprintf("reported     : %s bytes\n", format(REPORTED_BYTES, big.mark = ",")))
  cat(sprintf("elapsed      : %.1f s\n", elapsed))
  size_ok <- !is.na(on_disk) && on_disk == REPORTED_BYTES
  cat(sprintf("[TEST3 %s] on-disk size %s reported size\n",
              if (size_ok) "PASS" else "FAIL",
              if (size_ok) "==" else "!="))
  # Validate it is a readable parquet (schema + nrow only; view-safe)
  if (size_ok) {
    tbl <- tryCatch(arrow::read_parquet(DEST, as_data_frame = FALSE),
                    error = function(e) { cat("parquet read err:", conditionMessage(e), "\n"); NULL })
    if (!is.null(tbl)) {
      cat(sprintf("[TEST3] parquet OK: %s rows x %d cols\n",
                  format(tbl$num_rows, big.mark = ","), tbl$num_columns))
      # Report whether this file is view-typed (relevant to the SEPARATE utf8_view issue)
      type_strs <- vapply(seq_len(tbl$num_columns),
                          function(i) tbl$schema$field(i - 1L)$type$ToString(), character(1))
      view_cols <- sum(grepl("string_view|binary_view", type_strs))
      cat(sprintf("[TEST3] view-typed columns: %d (separate utf8_view concern)\n", view_cols))
    }
  }
}

# =====================================================================
# TEST 1 (H1 confirm): the ORIGINAL failing path + raised timeout.
# arrow::read_parquet(url) delegates to download.file(), which honors
# getOption('timeout'). Raise it to 600s and re-run the SAME call.
# =====================================================================
cat("\n=== TEST 1: arrow::read_parquet(url) with options(timeout=600) ===\n")
old_to <- getOption("timeout")
options(timeout = 600)
cat("timeout raised to:", getOption("timeout"), "s\n")
t1 <- Sys.time()
tbl1 <- tryCatch(
  arrow::read_parquet(URL, as_data_frame = FALSE),
  error = function(e) { cat("read_parquet(url) error:", conditionMessage(e), "\n"); NULL },
  warning = function(w) { cat("read_parquet(url) WARNING:", conditionMessage(w), "\n"); NULL }
)
if (!is.null(tbl1)) {
  e1 <- as.numeric(difftime(Sys.time(), t1, units = "secs"))
  cat(sprintf("[TEST1 PASS] arrow::read_parquet(url) completed: %s rows x %d cols in %.1f s\n",
              format(tbl1$num_rows, big.mark = ","), tbl1$num_columns, e1))
  cat("[H1 CONFIRMED] Same code path succeeds once timeout > transfer time.\n")
} else {
  cat("[TEST1 did not return a table — see message above]\n")
}
options(timeout = old_to)

cat("\n--- Diagnostic 02 complete ---\n")


# =============================================================================
# EXECUTION LOG
# =============================================================================
#
# Executed: 2026-07-11 19:26:12
# Command: Rscript /daaf/research/2026-07-11_FrameworkDev_MirrorParquetCompat/scripts/debug/02_diag-fetch-methods.R
# Duration: 682s
# Exit code: 0
#
# --- STDOUT ---
# 
# Attaching package: ‘arrow’
# 
# The following object is masked from ‘package:utils’:
# 
#     timestamp
# 
# Using libcurl 7.88.1 with OpenSSL/3.0.20
# === TEST 3: curl::multi_download() (robust large-file fetch) ===
# Download status: 0 done; 1 in progress (0 b/s). Total size: 15.99 Kb (0%)...Download status: 0 done; 1 in progress (1.44 Mb/s). Total size: 9.09 Mb (4%)...Download status: 0 done; 1 in progress (1.21 Mb/s). Total size: 13.99 Mb (7%)...Download status: 0 done; 1 in progress (1.02 Mb/s). Total size: 17.27 Mb (8%)...Download status: 0 done; 1 in progress (986.63 Kb/s). Total size: 21.20 Mb (10%)...Download status: 0 done; 1 in progress (905.26 Kb/s). Total size: 23.87 Mb (11%)...Download status: 0 done; 1 in progress (865.68 Kb/s). Total size: 27.17 Mb (13%)...Download status: 0 done; 1 in progress (809.87 Kb/s). Total size: 29.41 Mb (14%)...Download status: 0 done; 1 in progress (758.04 Kb/s). Total size: 32.01 Mb (15%)...Download status: 0 done; 1 in progress (720.94 Kb/s). Total size: 34.26 Mb (16%)...Download status: 0 done; 1 in progress (697.57 Kb/s). Total size: 36.79 Mb (17%)...Download status: 0 done; 1 in progress (672.03 Kb/s). Total size: 39.13 Mb (18%)...Download status: 0 done; 1 in progress (665.46 Kb/s). Total size: 42.02 Mb (20%)...Download status: 0 done; 1 in progress (639.97 Kb/s). Total size: 43.99 Mb (21%)...Download status: 0 done; 1 in progress (637.26 Kb/s). Total size: 47.24 Mb (22%)...Download status: 0 done; 1 in progress (631.50 Kb/s). Total size: 49.90 Mb (23%)...Download status: 0 done; 1 in progress (623.13 Kb/s). Total size: 52.43 Mb (25%)...Download status: 0 done; 1 in progress (617.38 Kb/s). Total size: 55.07 Mb (26%)...Download status: 0 done; 1 in progress (611.08 Kb/s). Total size: 57.95 Mb (27%)...Download status: 0 done; 1 in progress (601.74 Kb/s). Total size: 60.34 Mb (28%)...Download status: 0 done; 1 in progress (600.43 Kb/s). Total size: 62.95 Mb (29%)...Download status: 0 done; 1 in progress (606.62 Kb/s). Total size: 67.01 Mb (31%)...Download status: 0 done; 1 in progress (603.91 Kb/s). Total size: 70.11 Mb (33%)...Download status: 0 done; 1 in progress (610.10 Kb/s). Total size: 73.87 Mb (35%)...Download status: 0 done; 1 in progress (607.10 Kb/s). Total size: 77.03 Mb (36%)...Download status: 0 done; 1 in progress (608.11 Kb/s). Total size: 80.24 Mb (38%)...Download status: 0 done; 1 in progress (596.78 Kb/s). Total size: 82.95 Mb (39%)...Download status: 0 done; 1 in progress (587.75 Kb/s). Total size: 84.67 Mb (40%)...Download status: 0 done; 1 in progress (587.84 Kb/s). Total size: 87.97 Mb (41%)...Download status: 0 done; 1 in progress (581.65 Kb/s). Total size: 90.28 Mb (42%)...Download status: 0 done; 1 in progress (573.66 Kb/s). Total size: 92.25 Mb (43%)...Download status: 0 done; 1 in progress (580.91 Kb/s). Total size: 96.88 Mb (45%)...Download status: 0 done; 1 in progress (570.97 Kb/s). Total size: 98.33 Mb (46%)...Download status: 0 done; 1 in progress (562.41 Kb/s). Total size: 99.60 Mb (47%)...Download status: 0 done; 1 in progress (546.40 Kb/s). Total size: 100.52 Mb (47%)...Download status: 0 done; 1 in progress (538.29 Kb/s). Total size: 101.76 Mb (48%)...Download status: 0 done; 1 in progress (536.74 Kb/s). Total size: 104.50 Mb (49%)...Download status: 0 done; 1 in progress (530.11 Kb/s). Total size: 105.81 Mb (49%)...Download status: 0 done; 1 in progress (515.13 Kb/s). Total size: 106.19 Mb (50%)...Download status: 0 done; 1 in progress (508.03 Kb/s). Total size: 107.53 Mb (50%)...Download status: 0 done; 1 in progress (502.06 Kb/s). Total size: 109.26 Mb (51%)...Download status: 0 done; 1 in progress (511.85 Kb/s). Total size: 113.93 Mb (53%)...Download status: 0 done; 1 in progress (515.58 Kb/s). Total size: 117.33 Mb (55%)...Download status: 0 done; 1 in progress (527.79 Kb/s). Total size: 122.69 Mb (57%)...Download status: 0 done; 1 in progress (551.90 Kb/s). Total size: 130.98 Mb (61%)...Download status: 0 done; 1 in progress (631.94 Kb/s). Total size: 153.18 Mb (72%)...Download status: 0 done; 1 in progress (659.45 Kb/s). Total size: 163.50 Mb (76%)...Download status: 0 done; 1 in progress (656.06 Kb/s). Total size: 166.70 Mb (78%)...Download status: 0 done; 1 in progress (657.54 Kb/s). Total size: 170.67 Mb (80%)...Download status: 0 done; 1 in progress (651.19 Kb/s). Total size: 172.34 Mb (81%)...Download status: 0 done; 1 in progress (645.45 Kb/s). Total size: 173.97 Mb (81%)...Download status: 0 done; 1 in progress (637.44 Kb/s). Total size: 175.63 Mb (82%)...Download status: 0 done; 1 in progress (636.75 Kb/s). Total size: 179.58 Mb (84%)...Download status: 0 done; 1 in progress (629.03 Kb/s). Total size: 181.17 Mb (85%)...Download status: 0 done; 1 in progress (620.55 Kb/s). Total size: 182.80 Mb (85%)...Download status: 0 done; 1 in progress (611.73 Kb/s). Total size: 183.29 Mb (86%)...Download status: 0 done; 1 in progress (611.80 Kb/s). Total size: 186.71 Mb (87%)...Download status: 0 done; 1 in progress (606.69 Kb/s). Total size: 189.42 Mb (89%)...Download status: 0 done; 1 in progress (600.74 Kb/s). Total size: 191.39 Mb (90%)...Download status: 0 done; 1 in progress (595.15 Kb/s). Total size: 192.99 Mb (90%)...Download status: 0 done; 1 in progress (593.79 Kb/s). Total size: 195.96 Mb (92%)...Download status: 0 done; 1 in progress (583.98 Kb/s). Total size: 197.04 Mb (92%)...Download status: 0 done; 1 in progress (578.21 Kb/s). Total size: 198.37 Mb (93%)...Download status: 0 done; 1 in progress (573.98 Kb/s). Total size: 199.99 Mb (94%)...Download status: 0 done; 1 in progress (569.64 Kb/s). Total size: 201.67 Mb (94%)...Download status: 0 done; 1 in progress (568.52 Kb/s). Total size: 204.76 Mb (96%)...Download status: 0 done; 1 in progress (564.89 Kb/s). Total size: 206.55 Mb (97%)...Download status: 0 done; 1 in progress (557.63 Kb/s). Total size: 207.27 Mb (97%)...Download status: 0 done; 1 in progress (554.74 Kb/s). Total size: 209.12 Mb (98%)...Download status: 0 done; 1 in progress (553.96 Kb/s). Total size: 212.17 Mb (99%)...Download status: 1 done; 0 in progress. Total size: 213.83 Mb (100%)... done!             
# success      : TRUE
# status_code  : 200
# downloaded   : NULL bytes
# on-disk size : 224,216,539 bytes
# reported     : 224,216,539 bytes
# elapsed      : 397.1 s
# [TEST3 PASS] on-disk size == reported size
# [TEST3] parquet OK: 3,688,237 rows x 52 cols
# [TEST3] view-typed columns: 0 (separate utf8_view concern)
# 
# === TEST 1: arrow::read_parquet(url) with options(timeout=600) ===
# timeout raised to: 600 s
# [TEST1 PASS] arrow::read_parquet(url) completed: 3,688,237 rows x 52 cols in 282.9 s
# [H1 CONFIRMED] Same code path succeeds once timeout > transfer time.
# 
# --- Diagnostic 02 complete ---
#
# --- STDERR ---
# (captured in STDOUT above via 2>&1)
#
# =============================================================================
