#!/usr/bin/env bats
# ============================================================================
# Python/Marimo Reproducibility Verification decompiler tests
# ============================================================================
# Exercises the canonical DAAF Stage 9 Marimo source/log bundle contract,
# successful script reconstruction and re-execution, bounded legacy forms,
# path confinement, association validation, atomic intake, overwrite refusal,
# and static-only dangling-reference analysis. Every test uses a unique
# scripts/scratch/ workspace and removes it in teardown.
# ============================================================================

load 'test_helper'

setup() {
    command -v python3 >/dev/null 2>&1 || skip "python3 is not installed"

    ORIGINAL_DIR="$(pwd)"
    TEST_DIR="${REPO_ROOT}/scripts/scratch/repro-python-roundtrip-${BATS_TEST_NUMBER:-0}-$$"
    mkdir -p "${TEST_DIR}"
    cd "${TEST_DIR}" || return 1

    FIXTURE="${REPO_ROOT}/tests/fixtures/reproducibility_verification/canonical_stage9.py"
    DECOMPILER="${REPO_ROOT}/scripts/decompile_notebook.py"
    export ORIGINAL_DIR TEST_DIR FIXTURE DECOMPILER
}

teardown() {
    cd "${ORIGINAL_DIR}" || true
    rm -rf "${TEST_DIR}"
}

write_archive_prefix() {
    local notebook_path="$1"
    local source_path="$2"
    local header_path="$3"

    cat > "${notebook_path}" <<PY
#!/usr/bin/env python3
"""
Decompiler Security Fixture

This notebook DISPLAYS the executed scripts from the scripts/ directory.
It does NOT contain new analysis code.

Generated by notebook-assembler agent.
"""

import marimo

__generated_with = "0.10.19"
app = marimo.App(width="medium")

@app.cell
def _(mo):
    mo.md("""
    ### 5.1: Security Fixture

    **Script:** \`scripts/${header_path}\`
    **Output:** \`output/security-fixture.txt\`
    **Status:** CP1 PASSED
    """)
    return

@app.cell
def _():
    # SOURCE: ${source_path}
    # ===========================================================================
    # ARCHIVED SCRIPT CODE (commented out to prevent execution conflicts)
    # Full executable script preserved at: ${source_path}
    # ===========================================================================
    #
    # print("ARCHIVE CODE")
    #
    pass  # Cell must have executable statement
    return
PY
}

append_valid_log() {
    local notebook_path="$1"
    local script_name="$2"

    cat >> "${notebook_path}" <<PY

@app.cell
def _(mo):
    mo.accordion({"Execution Log (${script_name})": mo.md('''\`\`\`
EXECUTION LOG
Exit code: 0
\`\`\`''')})
    return
PY
}

write_archive() {
    local notebook_path="$1"
    local source_path="$2"
    local mode="${3:-valid}"
    local header_path="${4:-stage5_fetch/01_safe.py}"
    local script_name="${5:-${source_path##*/}}"

    write_archive_prefix "${notebook_path}" "${source_path}" "${header_path}"
    case "${mode}" in
        valid)
            append_valid_log "${notebook_path}" "${script_name}"
            ;;
        missing)
            ;;
        empty)
            cat >> "${notebook_path}" <<PY

@app.cell
def _(mo):
    mo.accordion({"Execution Log (${script_name})": mo.md('''\`\`\`

\`\`\`''')})
    return
PY
            ;;
        malformed)
            cat >> "${notebook_path}" <<PY

@app.cell
def _(mo):
    mo.accordion({"Execution Log (${script_name})": mo.md("not a fenced execution log")})
    return
PY
            ;;
        placeholder)
            cat >> "${notebook_path}" <<PY

@app.cell
def _(mo):
    mo.accordion({"Execution Log (${script_name})": mo.md('''\`\`\`
No execution log found
\`\`\`''')})
    return
PY
            ;;
        *)
            return 1
            ;;
    esac
}

append_bundle() {
    local notebook_path="$1"
    local source_path="$2"
    local include_log="${3:-yes}"
    local script_name="${source_path##*/}"

    cat >> "${notebook_path}" <<PY

@app.cell
def _(mo):
    mo.md("""
    ### 6.1: Second Security Fixture

    **Script:** \`scripts/${source_path}\`
    **Output:** \`output/second-security-fixture.txt\`
    **Status:** CP2 PASSED
    """)
    return

@app.cell
def _():
    # SOURCE: scripts/${source_path}
    # ===========================================================================
    # ARCHIVED SCRIPT CODE (commented out to prevent execution conflicts)
    # Full executable script preserved at: scripts/${source_path}
    # ===========================================================================
    #
    # print("SECOND ARCHIVE CODE")
    #
    pass  # Cell must have executable statement
    return
PY
    if [ "${include_log}" = "yes" ]; then
        append_valid_log "${notebook_path}" "${script_name}"
    fi
}

replace_once() {
    local target_file="$1"
    local old_text="$2"
    local new_text="$3"

    python3 - "${target_file}" "${old_text}" "${new_text}" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
old = sys.argv[2]
new = sys.argv[3]
text = path.read_text(encoding="utf-8")
if text.count(old) != 1:
    raise SystemExit(
        f"expected exactly one replacement target, found {text.count(old)}: {old!r}"
    )
path.write_text(text.replace(old, new, 1), encoding="utf-8")
PY
}

assert_rejected_without_outputs() {
    local notebook_path="$1"
    local output_root="$2"
    local expected_message="$3"

    run python3 "${DECOMPILER}" "${notebook_path}" "${output_root}"

    assert_failure
    assert_output --partial "${expected_message}"
    [ ! -e "${output_root}" ]
}

@test "canonical Stage 9 Marimo archive decompiles normalizes and re-executes" {
    local archive_path="${TEST_DIR}/canonical_stage9.py"
    local extracted_root="${TEST_DIR}/original_files/scripts"
    local extracted_script="${extracted_root}/stage5_fetch/01_write-fixture.py"
    local project_dir="${TEST_DIR}/reproduction_project"
    local repro_dir="${project_dir}/scripts/repro/stage5_fetch"
    local repro_script="${repro_dir}/01_write-fixture.py"

    cp "${FIXTURE}" "${archive_path}"
    replace_once \
        "${archive_path}" \
        $'--- STDOUT ---\nROUNDTRIP STATUS: PASSED' \
        $'--- STDOUT ---\nROUNDTRIP STATUS: PASSED\nHistorical project root: /daaf/research/original_python_fixture'

    run python3 "${DECOMPILER}" "${archive_path}" "${extracted_root}"

    assert_success
    assert_output --partial "Validated 1 source/log bundle(s)"
    assert_output --partial "Done. 1 scripts extracted"
    [ -f "${extracted_script}" ]
    [ -f "${extracted_root}/MANIFEST.md" ]
    grep -F 'PROJECT_DIR = Path("/daaf/research/original_python_fixture")' \
        "${extracted_script}"
    grep -F '# EXECUTION LOG' "${extracted_script}"
    grep -F '# ROUNDTRIP STATUS: PASSED' "${extracted_script}"
    grep -F '**Decompiled:** 1 scripts' "${extracted_root}/MANIFEST.md"
    grep -F '**Validated source/log associations:** 1' \
        "${extracted_root}/MANIFEST.md"
    grep -F '**Canonical bundles:** 1' "${extracted_root}/MANIFEST.md"

    run python3 "${REPO_ROOT}/scripts/normalize_project_dir.py" \
        "${extracted_root}" "${project_dir}"

    assert_success
    assert_output --partial "RESULT: 1 normalized, 0 unchanged, 0 no match"
    grep -F "PROJECT_DIR = Path(\"${project_dir}\")" "${extracted_script}"
    grep -F '/daaf/research/original_python_fixture' "${extracted_script}"

    run python3 "${REPO_ROOT}/scripts/audit_reproduction_paths.py" \
        "${extracted_root}" "/daaf/research/original_python_fixture" "${project_dir}"

    assert_success
    assert_output --partial '"overall": "MATCH"'
    assert_output --partial '"code": "ORIGINAL_ROOT_LOG_RESIDUE"'

    mkdir -p "${repro_dir}"
    sed '/^# EXECUTION LOG/,$d' "${extracted_script}" > "${repro_script}"
    ! grep -F '# EXECUTION LOG' "${repro_script}"

    run bash "${REPO_ROOT}/scripts/run_with_capture.sh" "${repro_script}"

    assert_success
    assert_output --partial "ROUNDTRIP STATUS: PASSED"
    [ -f "${project_dir}/output/roundtrip.txt" ]
    grep -Fx 'Python RV round trip' "${project_dir}/output/roundtrip.txt"
    grep -F '# EXECUTION LOG' "${repro_script}"
    grep -F '# Exit code: 0' "${repro_script}"
}

@test "documented wrapped accordion and legacy metadata path forms remain supported" {
    local notebook_path="${TEST_DIR}/legacy-wrapped.py"
    local output_root="${TEST_DIR}/legacy-wrapped-output"
    local extracted_script="${output_root}/stage5_fetch/01_legacy.py"

    cat > "${notebook_path}" <<'PY'
#!/usr/bin/env python3
"""
Legacy DAAF Stage 9 fixture

This notebook DISPLAYS the executed scripts from the scripts/ directory.
It does NOT contain new analysis code.
"""
import marimo
app = marimo.App(width="medium")

@app.cell
def _(mo):
    mo.md("""
    #### 5.1: Legacy Wrapped Fixture
    **Final Script:** `scripts/stage5_fetch/01_legacy.py`
    **Output:** `output/legacy.txt`
    **Status:** CP1 PASSED
    """)
    return

@app.cell
def _():
    # SOURCE: stage5_fetch/01_legacy.py
    # ===========================================================================
    # ARCHIVED SCRIPT CODE (commented out to prevent execution conflicts)
    # Full executable script preserved at: stage5_fetch/01_legacy.py
    # ===========================================================================
    #
    # print("LEGACY ARCHIVE CODE")
    #
    pass  # Cell must have executable statement

@app.cell
def _(mo):
    mo.accordion(
        {
            "Execution Log (01_legacy.py)": mo.md(
                '''```
# =============================================================================
# EXECUTION LOG
# =============================================================================
# Exit code: 0
```'''
            )
        }
    )
    return
PY

    run python3 "${DECOMPILER}" "${notebook_path}" "${output_root}"

    assert_success
    [ -f "${extracted_script}" ]
    grep -F 'print("LEGACY ARCHIVE CODE")' "${extracted_script}"
    grep -F '# EXECUTION LOG' "${extracted_script}"
    ! grep -F '# # EXECUTION LOG' "${extracted_script}"
    grep -F '**Bundles using bounded legacy metadata/path forms:** 1' \
        "${output_root}/MANIFEST.md"
}

@test "generic Marimo application and zero-script DAAF archive are rejected" {
    local generic_notebook="${TEST_DIR}/generic.py"
    local generic_output="${TEST_DIR}/generic-output"
    local zero_notebook="${TEST_DIR}/zero.py"
    local zero_output="${TEST_DIR}/zero-output"

    cat > "${generic_notebook}" <<'PY'
import marimo
app = marimo.App()
@app.cell
def _():
    print("ordinary marimo application")
PY
    assert_rejected_without_outputs \
        "${generic_notebook}" "${generic_output}" \
        "arbitrary marimo applications are not accepted"

    cat > "${zero_notebook}" <<'PY'
"""
This notebook DISPLAYS the executed scripts from the scripts/ directory.
It does NOT contain new analysis code.
Generated by notebook-assembler agent.
"""
import marimo
app = marimo.App()
@app.cell
def _(mo):
    mo.md("No archived scripts")
PY
    assert_rejected_without_outputs \
        "${zero_notebook}" "${zero_output}" "no valid script bundles found"
}

@test "missing empty malformed and placeholder execution logs are rejected" {
    local mode
    local notebook_path
    local output_root
    local expected_message

    for mode in missing empty malformed placeholder; do
        notebook_path="${TEST_DIR}/${mode}-log.py"
        output_root="${TEST_DIR}/${mode}-log-output"
        write_archive \
            "${notebook_path}" "scripts/stage5_fetch/01_safe.py" "${mode}"
        case "${mode}" in
            missing)
                expected_message="must be followed immediately"
                ;;
            empty)
                expected_message="execution log is empty"
                ;;
            malformed)
                expected_message="execution-log markdown must contain exactly one complete plain fenced body"
                ;;
            placeholder)
                expected_message="placeholder rather than archived execution evidence"
                ;;
        esac
        assert_rejected_without_outputs \
            "${notebook_path}" "${output_root}" "${expected_message}"
    done
}

@test "empty and whitespace-only archived Python source bodies are rejected atomically" {
    local notebook_path="${TEST_DIR}/empty-source.py"
    local output_root="${TEST_DIR}/empty-source-output"

    write_archive "${notebook_path}" "scripts/stage5_fetch/01_safe.py" valid
    replace_once \
        "${notebook_path}" \
        '    # print("ARCHIVE CODE")' \
        '    #    '

    assert_rejected_without_outputs \
        "${notebook_path}" "${output_root}" "archive source code is empty"
}

@test "all canonical execution-log placeholder classes are rejected case-insensitively" {
    local payload
    local notebook_path
    local output_root
    local case_index=0
    local -a placeholder_payloads=(
        $'=== EXECUTION LOG ===\n  NO EXECUTION LOG FOUND!!!  '
        '[TODO]'
        '--- tBd ---'
        '# *** Generic Placeholder ***'
        'Please paste the execution log here later.'
        'COPY the complete execution log from the script later!!!'
        '(add actual execution log below later)'
        'VERBATIM COPY FROM SCRIPT.'
    )

    for payload in "${placeholder_payloads[@]}"; do
        case_index=$((case_index + 1))
        notebook_path="${TEST_DIR}/placeholder-${case_index}.py"
        output_root="${TEST_DIR}/placeholder-${case_index}-output"
        write_archive "${notebook_path}" "scripts/stage5_fetch/01_safe.py" valid
        replace_once \
            "${notebook_path}" \
            $'EXECUTION LOG\nExit code: 0' \
            "${payload}"

        assert_rejected_without_outputs \
            "${notebook_path}" "${output_root}" \
            "placeholder rather than archived execution evidence"
    done
}

@test "substantive execution log containing a normal TODO word is accepted" {
    local notebook_path="${TEST_DIR}/substantive-todo-log.py"
    local output_root="${TEST_DIR}/substantive-todo-log-output"

    write_archive "${notebook_path}" "scripts/stage5_fetch/01_safe.py" valid
    replace_once \
        "${notebook_path}" \
        $'EXECUTION LOG\nExit code: 0' \
        $'Executed: 2026-07-16 19:00:00 UTC\nTODO checks completed successfully\nExit code: 0'

    run python3 "${DECOMPILER}" "${notebook_path}" "${output_root}"

    assert_success
    [ -f "${output_root}/stage5_fetch/01_safe.py" ]
    [ -f "${output_root}/MANIFEST.md" ]
}

@test "delayed mismatched and duplicate log associations are rejected" {
    local delayed_notebook="${TEST_DIR}/delayed-log.py"
    local delayed_output="${TEST_DIR}/delayed-log-output"
    local mismatch_notebook="${TEST_DIR}/mismatch-log.py"
    local mismatch_output="${TEST_DIR}/mismatch-log-output"
    local duplicate_notebook="${TEST_DIR}/duplicate-log.py"
    local duplicate_output="${TEST_DIR}/duplicate-log-output"

    write_archive \
        "${delayed_notebook}" "scripts/stage5_fetch/01_safe.py" missing
    cat >> "${delayed_notebook}" <<'PY'

@app.cell
def _(mo):
    mo.md("Narrative content delays the log")
    return
PY
    append_valid_log "${delayed_notebook}" "01_safe.py"
    assert_rejected_without_outputs \
        "${delayed_notebook}" "${delayed_output}" "must be followed immediately"

    write_archive \
        "${mismatch_notebook}" "scripts/stage5_fetch/01_safe.py" valid \
        "stage5_fetch/01_safe.py" "02_wrong.py"
    assert_rejected_without_outputs \
        "${mismatch_notebook}" "${mismatch_output}" "execution-log/source mismatch"

    write_archive \
        "${duplicate_notebook}" "scripts/stage5_fetch/01_safe.py" valid
    append_valid_log "${duplicate_notebook}" "01_safe.py"
    assert_rejected_without_outputs \
        "${duplicate_notebook}" "${duplicate_output}" "duplicate execution-log accordion"
}

@test "absolute backslash traversal leading-dash and extra-depth paths are rejected" {
    local source_path
    local notebook_path
    local output_root
    local case_index=0
    local -a unsafe_paths=(
        '/daaf/scripts/scratch/absolute-escape.py'
        'scripts/stage5_fetch\escaped.py'
        'scripts/stage5_fetch/../escaped.py'
        'scripts/stage5_fetch/-unsafe.py'
        'scripts/stage5_fetch/extra/escaped.py'
    )

    for source_path in "${unsafe_paths[@]}"; do
        case_index=$((case_index + 1))
        notebook_path="${TEST_DIR}/unsafe-${case_index}.py"
        output_root="${TEST_DIR}/unsafe-${case_index}-output"
        write_archive "${notebook_path}" "${source_path}" valid

        run python3 "${DECOMPILER}" "${notebook_path}" "${output_root}"

        assert_failure
        assert_output --partial "SOURCE"
        [ ! -e "${output_root}" ]
    done
}

@test "noncanonical stage and non-py extensions are rejected" {
    local notebook_path="${TEST_DIR}/invalid-stage.py"
    local output_root="${TEST_DIR}/invalid-stage-output"

    write_archive \
        "${notebook_path}" "scripts/stage4_plan/01_safe.py" valid
    assert_rejected_without_outputs \
        "${notebook_path}" "${output_root}" "noncanonical stage directory"

    notebook_path="${TEST_DIR}/invalid-extension.py"
    output_root="${TEST_DIR}/invalid-extension-output"
    write_archive \
        "${notebook_path}" "scripts/stage5_fetch/01_safe.R" valid
    assert_rejected_without_outputs \
        "${notebook_path}" "${output_root}" "does not end in .py"
}

@test "malformed and duplicate SOURCE markers are rejected" {
    local malformed_notebook="${TEST_DIR}/malformed-source.py"
    local malformed_output="${TEST_DIR}/malformed-source-output"
    local duplicate_notebook="${TEST_DIR}/duplicate-source-marker.py"
    local duplicate_output="${TEST_DIR}/duplicate-source-marker-output"

    cat > "${malformed_notebook}" <<'PY'
"""Generated by notebook-assembler agent."""
import marimo
app = marimo.App()
@app.cell
def _():
    # SOURCE scripts/stage5_fetch/01_safe.py
    pass  # Cell must have executable statement
PY
    assert_rejected_without_outputs \
        "${malformed_notebook}" "${malformed_output}" "malformed SOURCE marker"

    write_archive_prefix \
        "${duplicate_notebook}" "scripts/stage5_fetch/01_safe.py" \
        "stage5_fetch/01_safe.py"
    sed -i \
        '/# ARCHIVED SCRIPT CODE/i\    # SOURCE: scripts/stage5_fetch/01_safe.py' \
        "${duplicate_notebook}"
    append_valid_log "${duplicate_notebook}" "01_safe.py"
    assert_rejected_without_outputs \
        "${duplicate_notebook}" "${duplicate_output}" "duplicate SOURCE markers"
}

@test "duplicate source paths across otherwise valid bundles are rejected" {
    local notebook_path="${TEST_DIR}/duplicate-source.py"
    local output_root="${TEST_DIR}/duplicate-source-output"

    write_archive \
        "${notebook_path}" "scripts/stage5_fetch/01_safe.py" valid
    append_bundle "${notebook_path}" "stage5_fetch/01_safe.py" yes

    assert_rejected_without_outputs \
        "${notebook_path}" "${output_root}" "duplicate SOURCE path"
}

@test "header mismatch and unsafe uncommented archive content are rejected" {
    local mismatch_notebook="${TEST_DIR}/header-mismatch.py"
    local mismatch_output="${TEST_DIR}/header-mismatch-output"
    local live_notebook="${TEST_DIR}/live-content.py"
    local live_output="${TEST_DIR}/live-content-output"

    write_archive \
        "${mismatch_notebook}" "scripts/stage5_fetch/01_safe.py" valid \
        "stage5_fetch/02_other.py"
    assert_rejected_without_outputs \
        "${mismatch_notebook}" "${mismatch_output}" "script header/source mismatch"

    write_archive \
        "${live_notebook}" "scripts/stage5_fetch/01_safe.py" valid
    sed -i 's/    # print("ARCHIVE CODE")/    print("LIVE CODE")/' \
        "${live_notebook}"
    assert_rejected_without_outputs \
        "${live_notebook}" "${live_output}" "not safely comment-prefixed"
}

@test "later invalid bundle leaves no partial scripts or manifest" {
    local notebook_path="${TEST_DIR}/late-invalid.py"
    local output_root="${TEST_DIR}/late-invalid-output"

    write_archive \
        "${notebook_path}" "scripts/stage5_fetch/01_valid.py" valid \
        "stage5_fetch/01_valid.py"
    append_bundle "${notebook_path}" "stage6_clean/02_missing-log.py" no

    assert_rejected_without_outputs \
        "${notebook_path}" "${output_root}" "must be followed immediately"
    [ ! -e "${output_root}/stage5_fetch/01_valid.py" ]
    [ ! -e "${output_root}/MANIFEST.md" ]
}

@test "pre-existing output root is preserved and never merged or overwritten" {
    local output_root="${TEST_DIR}/existing-output"
    local sentinel="${output_root}/keep-me.txt"

    mkdir -p "${output_root}"
    printf '%s\n' 'preserve existing content' > "${sentinel}"

    run python3 "${DECOMPILER}" "${FIXTURE}" "${output_root}"

    assert_failure
    assert_output --partial "output directory already exists"
    grep -Fx 'preserve existing content' "${sentinel}"
    [ ! -e "${output_root}/stage5_fetch/01_write-fixture.py" ]
    [ ! -e "${output_root}/MANIFEST.md" ]
}

@test "dangling-reference analysis parses but never evaluates notebook-derived code" {
    local notebook_path="${TEST_DIR}/no-evaluation.py"
    local output_root="${TEST_DIR}/no-evaluation-output"
    local sentinel_path="${TEST_DIR}/must-not-be-created.txt"

    cat > "${notebook_path}" <<PY
#!/usr/bin/env python3
"""Generated by notebook-assembler agent."""
import marimo
app = marimo.App()

@app.cell
def _(mo):
    mo.md("""
    ### 5.1: Static Analysis Safety Fixture
    **Script:** \`scripts/stage5_fetch/01_untrusted.py\`
    **Output:** \`output/untrusted.txt\`
    **Status:** CP1 PASSED
    """)
    return

@app.cell
def _():
    # SOURCE: scripts/stage5_fetch/01_untrusted.py
    # ===========================================================================
    # ARCHIVED SCRIPT CODE (commented out to prevent execution conflicts)
    # Full executable script preserved at: scripts/stage5_fetch/01_untrusted.py
    # ===========================================================================
    #
    # from pathlib import Path
    # Path("${sentinel_path}").write_text("PWNED", encoding="utf-8")
    # undefined_review_prompt
    #
    pass  # Cell must have executable statement
    return

@app.cell
def _(mo):
    mo.accordion({"Execution Log (01_untrusted.py)": mo.md('''\`\`\`
EXECUTION LOG
Exit code: 0
\`\`\`''')})
    return
PY

    run python3 "${DECOMPILER}" "${notebook_path}" "${output_root}"

    assert_success
    assert_output --partial "dangling references: undefined_review_prompt"
    [ -f "${output_root}/stage5_fetch/01_untrusted.py" ]
    [ -f "${output_root}/MANIFEST.md" ]
    [ ! -e "${sentinel_path}" ]
}
